#!/usr/bin/fish
set filepath "$HOME/Pictures/Screenshots/$(date +%Y-%m)"
set filename "$(date +%d_%A_%T).png" 
mkdir -p "$filepath"

switch $argv
  case active
    set activearea $(hyprctl activewindow -j | jq -r '"\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"')
    grim -g "$activearea" "$filepath/$filename"
  case area
    hyprpicker -r -z &
    sleep 0.2
    grim -g "$(slurp)" "$filepath/$filename"
    pkill hyprpicker
  case output
    set output $(hyprctl -j activeworkspace | jq -r '(.monitor)') 
    grim -o "$output" "$filepath/$filename"
end

if test -e "$filepath/$filename"
  wl-copy < "$filepath/$filename"
  notify-send -t 1000 "Screenshot saved to $filepath/$filename"
end
