#!/usr/bin/fish
set filepath "$HOME/Pictures/Screenshots/$(date +%Y-%m)/$(date +%d_%A_%T).png"

switch $argv
  case active
    set activearea $(hyprctl activewindow -j | jq -r '"\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"')
    grim -g "$activearea" "$filepath"
  case area 
    grim -g "$(slurp)" "$filepath"
  case output
    set output $(hyprctl -j activeworkspace | jq -r '(.monitor)') 
    grim -o "$output" "$filepath"
end

if test -e "$filepath"
  wl-copy < "$filepath"
  notify-send -t 1000 "Screenshot saved to $filepath"
end
